version: "3.5"

services:
  pgsql:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "pgsql"
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    networks:
      - eadcorel

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    container_name: "adminer-ead"
    networks:
      - eadcorel

networks:
  eadcorel:
    driver: bridge

volumes:
  pg-data:
